version: '2.1'

services:

  cbl-db:
    container_name: cbl-db
    build:
      context: ../db
    volumes:
      - '../db/data:/var/lib/postgresql/data'
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: exit 0
  
  cbl-redis:
    container_name: cbl-redis
    build:
      context: ../redis
    ports:
      - 6379:6379  # expose ports - HOST:CONTAINER
    healthcheck:
      test: exit 0


  cbl-service:
    container_name: cbl-service
    build:
      context: ../service
    volumes:
      - '../service:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@cbl-db:5432/cbl_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@cbl-db:5432/cbl_test
      - SECRET_KEY=${FLASK_KEY}
      - JWT_SECRET_KEY=${JWT_KEY}
      - MAILGUN_KEY=${MAILGUN_KEY}
      - MAILGUN_URL=${MAILGUN_URL}
      - MAILGUN_FROM=${MAILGUN_FROM}
      - BASE_URL=${BASE_URL}
    depends_on:
      cbl-db:
        condition: service_healthy
      cbl-redis:
        condition: service_healthy
    links:
      - cbl-db
      - cbl-redis

  # nginx:
  #   container_name: nginx
  #   build: ./nginx/
  #   restart: always
  #   ports:
  #     - 80:80
  #   depends_on:
  #     cbl-service:
  #       condition: service_started
  #   #  web-service:
  #    #   condition: service_started
  #   links:
  #     - cbl-service
  #   #  - web-service

  # web-service:
  #   container_name: web-service
  #   build:
  #     context: ../flask-microservices-client
  #     dockerfile: Dockerfile-local
  #   volumes:
  #     - '../flask-microservices-client:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - '9000:9000' # expose ports - HOST:CONTAINER
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
  #   depends_on:
  #     users-service:
  #       condition: service_started
  #   links:
  #     - users-service
