version: '2.1'

services:

  cbl-db:
    container_name: cbl-db
    build:
      context: ../service/project/db
    ports:
      - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  cbl-service:
    container_name: cbl-service
    build:
      context: ../service
      dockerfile: Dockerfile-local
    volumes:
      - '/hosthome/chris/Dev/CBL-Music/service:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      cbl-db:
        condition: service_healthy
    links:
      - cbl-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      cbl-service:
        condition: service_started
    #  web-service:
     #   condition: service_started
    links:
      - cbl-service
    #  - web-service

  # web-service:
  #   container_name: web-service
  #   build:
  #     context: ../flask-microservices-client
  #     dockerfile: Dockerfile-local
  #   volumes:
  #     - '../flask-microservices-client:/usr/src/app'
  #     - '/usr/src/app/node_modules'
  #   ports:
  #     - '9000:9000' # expose ports - HOST:CONTAINER
  #   environment:
  #     - NODE_ENV=development
  #     - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
  #   depends_on:
  #     users-service:
  #       condition: service_started
  #   links:
  #     - users-service

  # swagger:
  #   container_name: swagger
  #   build:
  #     context: ../flask-microservices-swagger
  #   ports:
  #     - '8080:8080' # expose ports - HOST:CONTAINER
  #   environment:
  #     - API_URL=https://raw.githubusercontent.com/realpython/flask-microservices-swagger/master/swagger.json
  #   depends_on:
  #     users-service:
  #       condition: service_started
